### ISSUE TITLE
qcint fails several libcint tests

### ISSUE THREAD

**Issue by oon3m0oo** [sunqm/qcint#3]
qcint fails many of the tests in libcint/testsuite/test_cint.py, sometimes with large precision issues.  I've also seen this directly in switching from libcint to qcint, where it gives vastly different results when using pyscf.  I've traced the start of the problems back to when quadmath support was added.  Disabling quadmath resolve some, but not all issues.

The last known good commit (with quadmath disabled) was 7af6bee; all the qcint v3 changes started introducing numerical instability.

**Comment by sunqm** [comment]
As you noticed, whether to enable quadmath is the main cause of the numerical problem. Quadmath is used to compute the roots of Rys polynomial. Numerical instability was observed when diffused high angular functions are presented in the basis functions.

In the qcint v3 implementation, I used polynomial fitting functions for certain numerical quadrature instead of solving linear equations. The parameters of the polynomial were generated based on the results of quadruple precision. In the libcint implementation, depending on the level of quadrature, the roots were computed either with double precision, extended precision or quadruple precision. The two implementations will have small numerical discrepancy, no matter whether you enable quadmath or not.

In my experience, the numerical discrepancy does not have noticeable effects for most non-relativistic basis in the non-relativistic calculations. But a noticeable difference can be found in the Coulomb/Gaunt/Breit integrals with small component basis functions.  Is this the case you got?

Since it's generally a numerical precision problem, I don't have an optimal solution. Quadmath may be more reliable and should be used to compute the roots whenever possible. If the round-off discrepancy matters, there are two possible solutions I can imagine. One is to add a conditional compiling option in libcint to enable quadmath at the same place as that in qcint.  The other is a conditional compiling to use the same precision for Rys quadrature in qcint as in libcint.

**Comment by oon3m0oo** [comment]
Thanks for the detailed response!  However, my point is that even **after disabling quadmath**, there are still several errors.  Just running test_cint.py fails for many cases.  One particular calculation I was trying, a fairly small system of C and H (2-Butyne), using CCSD with the cc-pVTZ basis, went off by a few orders of magnitude just by switching to qcint (with no quadmath).

**Comment by sunqm** [comment]
No matter whether you enable quadmath or not, you will see a few fails in test_cint.  Some parameters are hardcoded in qcint which were based on quadmath data.  They are computed on the fly in libcint, from which the test_cint.py was created. The difference can be only observed on high angular moment functions (like g, h functions), or high-order derivatives (like ssss type integrals of relativistic theory).

When comparing the error of integrals, CCSD is not a good metric since it can be affected by many facts, like the SCF orbitals, DIIS round off error, the condition number of the overlap matrix. My experience is that the uncertainty of CCSD energy is roughly at the order of 1/cond(S), regardless how the integrals are computed.

Comparing to CCSD energy, SCF results are a better metric to measure the error in integrals. However, the trust region may be just ~12 decimal places, depending on the round-off error in diagonalization and DIIS and other accumulated numerical errors.
